package view;
import com.ConvertDokterToObject;
import com.ConvertPasienToObject;
import com.ConvertAkunToObject;
import com.Pasien;
import com.Dokter;
import com.Akun;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
/**
 *
 * @author Ivan Pakpahan
 */
public class MainFormRS extends javax.swing.JFrame {
    /**
     * Creates new form MainFormRS
     */
    public MainFormRS() {
        initComponents();
        setDataPasien();
        setDataDokter();
        setDataAkun();
        
    }
    private void setDataPasien(){
        ConvertPasienToObject cptb = new ConvertPasienToObject();
        String[][] dataPasien = cptb.getPasien();
        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
                dataPasien,
                new String [] {"ID", "Nama", "Nomor Hp", "Alamat","Status"})
        );
    }
    private void setDataDokter(){
        ConvertDokterToObject cdtb = new ConvertDokterToObject();
        String[][] dataDokter = cdtb.getDokter();
        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
                dataDokter,
                new String [] {"ID", "Nama", "Spesialis", "Alamat"})
        );
    }
    private void setDataAkun(){
        ConvertAkunToObject catb = new ConvertAkunToObject();
        String[][] dataAkun = catb.getAkun();
        tblAkun.setModel(new javax.swing.table.DefaultTableModel(
                dataAkun,
                new String [] {"ID", "Username", "Password", "Level","Nama","Nomor Hp","Alamat"})
        );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlPasien = new javax.swing.JPanel();
        pnlInputPasien = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama_Pasien = new javax.swing.JTextField();
        txtNo_HpPasien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamatPasien = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblId_Pasien = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ComboStatus = new javax.swing.JComboBox<>();
        LblStatusPasien = new javax.swing.JLabel();
        pnlTblPasien = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPasien = new javax.swing.JTable();
        pnlDokter = new javax.swing.JPanel();
        pnlInputDokter = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblId_dokter = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNama_Dokter = new javax.swing.JTextField();
        txtSpesialis_Dokter = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlamat_Dokter = new javax.swing.JTextArea();
        simpanDok = new javax.swing.JButton();
        UpdateDok = new javax.swing.JButton();
        HapusDok = new javax.swing.JButton();
        ResetDok = new javax.swing.JButton();
        pnlTblDokter = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDokter = new javax.swing.JTable();
        pnlAkun = new javax.swing.JPanel();
        pnlInputAkun = new javax.swing.JPanel();
        lblLevel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblId_Akun = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtNamaAkun = new javax.swing.JTextField();
        txtNomorHpAkun = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAlamatAkun = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        pnlTblAkun = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblAkun = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);
        jToolBar1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pasien48.png"))); // NOI18N
        jButton1.setText("Data Pasien");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dokter48.png"))); // NOI18N
        jButton2.setText("Data Dokter");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Akun48.png"))); // NOI18N
        jButton3.setText("Data Admin");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        pnlUtama.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setText("Halo Selamat Datang....");
        pnlUtama.add(jLabel1, "card2");

        pnlInputPasien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        pnlInputPasien.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nomor Hp");
        pnlInputPasien.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Alamat");
        pnlInputPasien.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Status");
        pnlInputPasien.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtNama_Pasien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlInputPasien.add(txtNama_Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 220, -1));

        txtNo_HpPasien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlInputPasien.add(txtNo_HpPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 220, -1));

        txtAlamatPasien.setColumns(20);
        txtAlamatPasien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAlamatPasien.setRows(5);
        jScrollPane1.setViewportView(txtAlamatPasien);

        pnlInputPasien.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 220, -1));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        pnlInputPasien.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 100, 30));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setText("Ubah");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlInputPasien.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("ID");
        pnlInputPasien.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblId_Pasien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlInputPasien.add(lblId_Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 40, 20));

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        pnlInputPasien.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 80, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnlInputPasien.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 100, 30));

        ComboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Merah", "Kuning", "Hijau", "Putih", "Hitam" }));
        ComboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboStatusActionPerformed(evt);
            }
        });
        pnlInputPasien.add(ComboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        LblStatusPasien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblStatusPasien.setText(".");
        pnlInputPasien.add(LblStatusPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 40, 20));

        tblPasien.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPasien);

        javax.swing.GroupLayout pnlTblPasienLayout = new javax.swing.GroupLayout(pnlTblPasien);
        pnlTblPasien.setLayout(pnlTblPasienLayout);
        pnlTblPasienLayout.setHorizontalGroup(
            pnlTblPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblPasienLayout.setVerticalGroup(
            pnlTblPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblPasienLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPasienLayout = new javax.swing.GroupLayout(pnlPasien);
        pnlPasien.setLayout(pnlPasienLayout);
        pnlPasienLayout.setHorizontalGroup(
            pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasienLayout.createSequentialGroup()
                .addComponent(pnlInputPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTblPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPasienLayout.setVerticalGroup(
            pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasienLayout.createSequentialGroup()
                .addGroup(pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTblPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlInputPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlPasien, "cardPasien");

        jLabel7.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        jLabel7.setText("ID");

        lblId_dokter.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        jLabel10.setText("Nama");

        jLabel11.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        jLabel11.setText("Spesialis");

        jLabel12.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        jLabel12.setText("Alamat");

        txtNama_Dokter.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N

        txtSpesialis_Dokter.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N

        txtAlamat_Dokter.setColumns(20);
        txtAlamat_Dokter.setFont(new java.awt.Font("Garamond", 0, 16)); // NOI18N
        txtAlamat_Dokter.setRows(5);
        jScrollPane3.setViewportView(txtAlamat_Dokter);

        simpanDok.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        simpanDok.setText("Simpan");
        simpanDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanDokActionPerformed(evt);
            }
        });

        UpdateDok.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        UpdateDok.setText("Update");
        UpdateDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDokActionPerformed(evt);
            }
        });

        HapusDok.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        HapusDok.setText("Hapus");
        HapusDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusDokActionPerformed(evt);
            }
        });

        ResetDok.setFont(new java.awt.Font("Garamond", 0, 14)); // NOI18N
        ResetDok.setText("Reset");
        ResetDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetDokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInputDokterLayout = new javax.swing.GroupLayout(pnlInputDokter);
        pnlInputDokter.setLayout(pnlInputDokterLayout);
        pnlInputDokterLayout.setHorizontalGroup(
            pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputDokterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpanDok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateDok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HapusDok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResetDok))
                    .addGroup(pnlInputDokterLayout.createSequentialGroup()
                        .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10))
                        .addGap(71, 71, 71)
                        .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama_Dokter)
                            .addComponent(txtSpesialis_Dokter)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addGroup(pnlInputDokterLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblId_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlInputDokterLayout.setVerticalGroup(
            pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputDokterLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblId_dokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama_Dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpesialis_Dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(71, 71, 71)
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanDok)
                    .addComponent(UpdateDok)
                    .addComponent(HapusDok)
                    .addComponent(ResetDok))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jScrollPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseClicked(evt);
            }
        });

        tblDokter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDokterMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDokter);

        javax.swing.GroupLayout pnlTblDokterLayout = new javax.swing.GroupLayout(pnlTblDokter);
        pnlTblDokter.setLayout(pnlTblDokterLayout);
        pnlTblDokterLayout.setHorizontalGroup(
            pnlTblDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblDokterLayout.setVerticalGroup(
            pnlTblDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblDokterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout pnlDokterLayout = new javax.swing.GroupLayout(pnlDokter);
        pnlDokter.setLayout(pnlDokterLayout);
        pnlDokterLayout.setHorizontalGroup(
            pnlDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInputDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTblDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlDokterLayout.setVerticalGroup(
            pnlDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDokterLayout.createSequentialGroup()
                .addComponent(pnlInputDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlTblDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlUtama.add(pnlDokter, "cardDokter");

        pnlInputAkun.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblLevel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel8.setText("ID");

        jLabel13.setText("Username");

        jLabel14.setText("Password");

        jLabel15.setText("Nama");

        jLabel16.setText("Nomor Hp");

        jLabel17.setText("Alamat");

        txtAlamatAkun.setColumns(20);
        txtAlamatAkun.setRows(5);
        jScrollPane5.setViewportView(txtAlamatAkun);

        jButton5.setText("Simpan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Hapus");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Reset");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInputAkunLayout = new javax.swing.GroupLayout(pnlInputAkun);
        pnlInputAkun.setLayout(pnlInputAkunLayout);
        pnlInputAkunLayout.setHorizontalGroup(
            pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputAkunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputAkunLayout.createSequentialGroup()
                        .addGroup(pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(31, 31, 31)
                        .addGroup(pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addGroup(pnlInputAkunLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblId_Akun, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLevel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtUsername)
                            .addComponent(txtPassword)
                            .addComponent(txtNamaAkun)
                            .addComponent(txtNomorHpAkun)))
                    .addGroup(pnlInputAkunLayout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInputAkunLayout.setVerticalGroup(
            pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputAkunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblId_Akun)
                    .addComponent(lblLevel))
                .addGap(18, 18, 18)
                .addGroup(pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNamaAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtNomorHpAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tblAkun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAkunMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblAkun);

        javax.swing.GroupLayout pnlTblAkunLayout = new javax.swing.GroupLayout(pnlTblAkun);
        pnlTblAkun.setLayout(pnlTblAkunLayout);
        pnlTblAkunLayout.setHorizontalGroup(
            pnlTblAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblAkunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblAkunLayout.setVerticalGroup(
            pnlTblAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblAkunLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAkunLayout = new javax.swing.GroupLayout(pnlAkun);
        pnlAkun.setLayout(pnlAkunLayout);
        pnlAkunLayout.setHorizontalGroup(
            pnlAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAkunLayout.createSequentialGroup()
                .addComponent(pnlInputAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTblAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAkunLayout.setVerticalGroup(
            pnlAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAkunLayout.createSequentialGroup()
                .addGroup(pnlAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTblAkun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInputAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlUtama.add(pnlAkun, "cardAkun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardPasien");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardDokter");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardAkun");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasienMouseClicked
        // TODO add your handling code here:
        int row = tblPasien.getSelectedRow();
        String id_pasien = tblPasien.getValueAt(row, 0).toString();
        String nama = tblPasien.getValueAt(row, 1).toString();
        String no_hp = tblPasien.getValueAt(row, 2).toString();
        String alamat = tblPasien.getValueAt(row, 3).toString();
        String status = tblPasien.getValueAt(row, 4).toString();
        lblId_Pasien.setText(id_pasien);
        txtNama_Pasien.setText(nama);
        txtNo_HpPasien.setText(no_hp);
        txtAlamatPasien.setText(alamat);
        LblStatusPasien.setText(status);
    }//GEN-LAST:event_tblPasienMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        //String id = lblId_Pasien.getText();
        //int id_pasien = Integer.parseInt(id);
        String nama = txtNama_Pasien.getText();
        String no_hp = txtNo_HpPasien.getText();
        String alamat = txtAlamatPasien.getText();
        String status = LblStatusPasien.getText();//
        Pasien pas = new Pasien(0,nama, no_hp, alamat,status);
        exec.ExecutePasien ePas = new exec.ExecutePasien();
        int hasil = ePas.insertData(pas);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDataPasien();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String id_pasien = lblId_Pasien.getText();
        exec.ExecutePasien ePas = new exec.ExecutePasien();
        int hasil = ePas.hapusData(id_pasien);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus"); 
            setDataPasien();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = lblId_Pasien.getText();
        int id_pasien = Integer.parseInt(id);
        String nama = txtNama_Pasien.getText();
        String alamat = txtAlamatPasien.getText();
        String status = LblStatusPasien.getText();
        String no_hp = txtNo_HpPasien.getText();
        Pasien pas = new Pasien(id_pasien,nama, no_hp, alamat,status);
        exec.ExecutePasien ePas = new exec.ExecutePasien();
        int hasil = ePas.ubahData(pas);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDataPasien();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDokterMouseClicked
        // TODO add your handling code here:
        int row = tblDokter.getSelectedRow();
        String id_dok = tblDokter.getValueAt(row, 0).toString();
        String nama = tblDokter.getValueAt(row, 1).toString();
        String no_hp = tblDokter.getValueAt(row, 2).toString();
        String alamat = tblDokter.getValueAt(row, 3).toString();
        lblId_dokter.setText(id_dok);
        txtNama_Dokter.setText(nama);
        txtSpesialis_Dokter.setText(no_hp);
        txtAlamat_Dokter.setText(alamat);
    }//GEN-LAST:event_tblDokterMouseClicked

    private void jScrollPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4MouseClicked

    private void simpanDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanDokActionPerformed
        // TODO add your handling code here:
        String nama = txtNama_Dokter.getText();
        String spesialis = txtSpesialis_Dokter.getText();
        String alamat = txtAlamat_Dokter.getText();
        Dokter dok = new Dokter(0,nama, spesialis, alamat);
        exec.ExecuteDokter eDok = new exec.ExecuteDokter();
        int hasil = eDok.insertData(dok);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDataDokter();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_simpanDokActionPerformed

    private void UpdateDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDokActionPerformed
        // TODO add your handling code here:
        String id = lblId_dokter.getText();
        int id_dok = Integer.parseInt(id);
        String nama = txtNama_Dokter.getText();
        String alamat = txtAlamat_Dokter.getText();
        String spesialis = txtSpesialis_Dokter.getText();
        Dokter dok = new Dokter(id_dok,nama, spesialis, alamat);
        exec.ExecuteDokter eDok = new exec.ExecuteDokter();
        int hasil = eDok.ubahData(dok);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDataDokter();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
    }//GEN-LAST:event_UpdateDokActionPerformed

    private void HapusDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusDokActionPerformed
        // TODO add your handling code here:
        String id_dok = lblId_dokter.getText();
        exec.ExecuteDokter eDok = new exec.ExecuteDokter();
        int hasil = eDok.hapusData(id_dok);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus"); 
            setDataDokter();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_HapusDokActionPerformed

    private void ResetDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetDokActionPerformed
        // TODO add your handling code here:
        hapus2();
    }//GEN-LAST:event_ResetDokActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String pass = txtPassword.getText();
        String level = "Admin";
        String nama = txtNamaAkun.getText();
        String no_hp = txtNomorHpAkun.getText();
        String alamat = txtAlamatAkun.getText();
        Akun akun = new Akun(0,username,pass,level,nama,no_hp,alamat);
        exec.ExecuteAkun eKun = new exec.ExecuteAkun();
        int hasil = eKun.insertData(akun);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDataAkun();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAkunMouseClicked
        // TODO add your handling code here:
        int row = tblAkun.getSelectedRow();
        String id_akun = tblAkun.getValueAt(row, 0).toString();
        String username = tblAkun.getValueAt(row, 1).toString();
        String pass = tblAkun.getValueAt(row, 2).toString();
        String level = tblAkun.getValueAt(row, 3).toString();
        String nama = tblAkun.getValueAt(row, 4).toString();
        String no_hp = tblAkun.getValueAt(row, 5).toString();
        String alamat = tblAkun.getValueAt(row, 6).toString();
        lblId_Akun.setText(id_akun);
        txtUsername.setText(username);
        txtPassword.setText(pass);
        lblLevel.setText(level);
        txtNamaAkun.setText(nama);
        txtNomorHpAkun.setText(no_hp);
        txtAlamatAkun.setText(alamat);
    }//GEN-LAST:event_tblAkunMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String id = lblId_Akun.getText();
        int id_akun = Integer.parseInt(id);
        String username = txtUsername.getText();
        String pass = txtPassword.getText();
        String nama = txtNamaAkun.getText();
        String no_hp = txtNomorHpAkun.getText();
        String alamat = txtAlamatAkun.getText();
        Akun akun = new Akun(id_akun,username,pass,"Admin",nama,no_hp, alamat);
        exec.ExecuteAkun eKun = new exec.ExecuteAkun();
        int hasil = eKun.ubahData(akun);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDataAkun();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        hapus3();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String id_akun = lblId_Akun.getText();
        exec.ExecuteAkun eKun = new exec.ExecuteAkun();
        int hasil = eKun.hapusData(id_akun);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus"); 
            setDataAkun();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void ComboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboStatusActionPerformed
        // TODO add your handling code here:
        String kode;
        if (ComboStatus.getSelectedIndex()==0){
            kode = "Merah";
            LblStatusPasien.setText(kode);
        }else if (ComboStatus.getSelectedIndex()==1){
            kode = "Kuning";
            LblStatusPasien.setText(kode);
        }else if (ComboStatus.getSelectedIndex()==2){
            kode = "Hijau";
            LblStatusPasien.setText(kode);
        }else if (ComboStatus.getSelectedIndex()==3){
            kode = "Putih";
            LblStatusPasien.setText(kode);
        }else if (ComboStatus.getSelectedIndex()==4){
            kode = "Hitam";
            LblStatusPasien.setText(kode);
        }
    }//GEN-LAST:event_ComboStatusActionPerformed
    private void hapus(){
        txtNama_Pasien.setText("");
        txtAlamatPasien.setText("");
        LblStatusPasien.setText("");
        txtNo_HpPasien.setText("");
        lblId_Pasien.setText("");
    }
    private void hapus2(){
        txtNama_Dokter.setText("");
        txtAlamat_Dokter.setText("");
        txtSpesialis_Dokter.setText("");
        lblId_dokter.setText("");
    }
    private void hapus3(){
        txtNamaAkun.setText("");
        txtAlamatAkun.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtAlamatAkun.setText("");
        lblLevel.setText("");
        lblId_Akun.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormRS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormRS().setVisible(true);
            }
        });
    }
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboStatus;
    private javax.swing.JButton HapusDok;
    private javax.swing.JLabel LblStatusPasien;
    private javax.swing.JButton ResetDok;
    private javax.swing.JButton UpdateDok;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblId_Akun;
    private javax.swing.JLabel lblId_Pasien;
    private javax.swing.JLabel lblId_dokter;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JPanel pnlAkun;
    private javax.swing.JPanel pnlDokter;
    private javax.swing.JPanel pnlInputAkun;
    private javax.swing.JPanel pnlInputDokter;
    private javax.swing.JPanel pnlInputPasien;
    private javax.swing.JPanel pnlPasien;
    private javax.swing.JPanel pnlTblAkun;
    private javax.swing.JPanel pnlTblDokter;
    private javax.swing.JPanel pnlTblPasien;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JButton simpanDok;
    private javax.swing.JTable tblAkun;
    private javax.swing.JTable tblDokter;
    private javax.swing.JTable tblPasien;
    private javax.swing.JTextArea txtAlamatAkun;
    private javax.swing.JTextArea txtAlamatPasien;
    private javax.swing.JTextArea txtAlamat_Dokter;
    private javax.swing.JTextField txtNamaAkun;
    private javax.swing.JTextField txtNama_Dokter;
    private javax.swing.JTextField txtNama_Pasien;
    private javax.swing.JTextField txtNo_HpPasien;
    private javax.swing.JTextField txtNomorHpAkun;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSpesialis_Dokter;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
