package view;
import com.ConvertDokterToObject;
import com.ConvertPasienToObject;
import com.ConvertAdminToObject;
import com.ConvertSuratToObject;
import com.Pasien;
import com.Dokter;
import com.Admin;
import db.ConnectionManager;
import exec.ExecutePasien;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable.PrintMode;
/**
 *
 * @author Ivan Pakpahan
 */
public class MFormAdmin extends javax.swing.JFrame {
    /**
     * Creates new form MainFormRS
     */
    public MFormAdmin() {
        initComponents();
        setDataPasien();
        setDataDokter();
        setDataAdmin();
        setDataSurat();
        
    }
    private void setDataPasien(){
        ConvertPasienToObject cptb = new ConvertPasienToObject();
        String[][] dataPasien = cptb.getPasien();
        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
                dataPasien,
                new String [] {"ID", "Nama", "Alamat","Nomor Hp","Status","Ruang"})
        );
    }
    private void setDataPasien1(){
        ConvertPasienToObject cptb = new ConvertPasienToObject();
        String id_pasien = txtCariPasien.getText();
        String[][] dataPasien = cptb.getOnePasien(id_pasien);
        tblPasien.setModel(new javax.swing.table.DefaultTableModel(dataPasien,new String [] {"ID", "Nama", "Alamat","Nomor Hp","Status","Ruang"})
        );
    }
    
    private void setDataDokter(){
        ConvertDokterToObject cdtb = new ConvertDokterToObject();
        String[][] dataDokter = cdtb.getDokter();
        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
                dataDokter,
                new String [] {"ID", "Nama", "Spesialis","No Hp", "Alamat","Username","Password","Level"})
        );
    }
    private void setDataDokter1(){
        ConvertDokterToObject cdtb = new ConvertDokterToObject();
        String id_dokter = txtCariDokter.getText();
        String[][] dataDokter = cdtb.getOneDokter(id_dokter);
        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
                dataDokter,
                new String [] {"ID", "Nama", "Spesialis","No Hp", "Alamat","Username","Password","Level"})
        );
    }
    private void setDataAdmin(){
        ConvertAdminToObject catb = new ConvertAdminToObject();
        String[][] dataAdmin = catb.getAdmin();
        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
                dataAdmin,
                new String [] {"ID", "Nama", "Username", "Password","Level","Nomor Hp","Email","Alamat"})
        );
    }
    private void setDataAdmin1(){
        ConvertAdminToObject catb = new ConvertAdminToObject();
        String id_admin = txtCariAdmin.getText();
        String[][] dataAdmin = catb.getOneAdmin(id_admin);
        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
                dataAdmin,
                new String [] {"ID", "Nama", "Username", "Password","Level","Nomor Hp","Email","Alamat"})
        );
    }
    private void setDataSurat(){
        ConvertSuratToObject cstb = new ConvertSuratToObject();
        String[][] dataSurat = cstb.getSurat();
        tblSurat.setModel(new javax.swing.table.DefaultTableModel(
                dataSurat,
                new String [] {"ID", "Keterangan", "ID Dokter", "ID Pasien"})
        );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        pnlUtama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlPasien = new javax.swing.JPanel();
        pnlInputPasien = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama_Pasien = new javax.swing.JTextField();
        txtNo_HpPasien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamatPasien = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblId_Pasien = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ComboStatus = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        TxtNoRuangan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pnlTblPasien = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPasien = new javax.swing.JTable();
        txtCariPasien = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        pnlDokter = new javax.swing.JPanel();
        pnlInputDokter = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblId_dokter = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNama_Dokter = new javax.swing.JTextField();
        txtSpesialis_Dokter = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlamat_Dokter = new javax.swing.JTextArea();
        simpanDok = new javax.swing.JButton();
        UpdateDok = new javax.swing.JButton();
        HapusDok = new javax.swing.JButton();
        ResetDok = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtUsernameDok = new javax.swing.JTextField();
        txtPasswordDok = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtNoHpDok = new javax.swing.JTextField();
        lvlDokter = new javax.swing.JLabel();
        pnlTblDokter = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDokter = new javax.swing.JTable();
        txtCariDokter = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        pnlAdmin = new javax.swing.JPanel();
        pnlInputAdmin = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lblId_Akun = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtNamaAkun = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtAlamatAkun = new javax.swing.JTextArea();
        simpanDok1 = new javax.swing.JButton();
        UpdateDok1 = new javax.swing.JButton();
        HapusDok1 = new javax.swing.JButton();
        ResetDok1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtNomorHpAkun = new javax.swing.JTextField();
        lblLevel = new javax.swing.JLabel();
        txtEmailAdmin = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        pnlTblAdmin = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblAdmin = new javax.swing.JTable();
        txtCariAdmin = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlSurat = new javax.swing.JPanel();
        pnlTampilSurat = new javax.swing.JPanel();
        lblLevel1 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblSurat = new javax.swing.JTable();
        txtCariAdmin1 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pasien.png"))); // NOI18N
        jButton1.setText("Data Pasien");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Dokter.png"))); // NOI18N
        jButton2.setText("Data Dokter");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Admin.png"))); // NOI18N
        jButton3.setText("Data Admin");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ST.png"))); // NOI18N
        jButton9.setText("Surat Tindakan");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Layanan.png"))); // NOI18N
        jButton10.setText("Laporan");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton10);

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Garamond", 1, 12)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Pembayaran.png"))); // NOI18N
        jButton11.setText("Pembayaran");
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton11);

        pnlUtama.setBackground(new java.awt.Color(255, 255, 255));
        pnlUtama.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        jLabel1.setText("Selamat datang Admin ...");
        pnlUtama.add(jLabel1, "card2");

        pnlPasien.setBackground(new java.awt.Color(255, 255, 255));

        pnlInputPasien.setBackground(new java.awt.Color(255, 255, 255));
        pnlInputPasien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        pnlInputPasien.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nomor Hp");
        pnlInputPasien.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Alamat");
        pnlInputPasien.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Status");
        pnlInputPasien.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtNama_Pasien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlInputPasien.add(txtNama_Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 220, -1));

        txtNo_HpPasien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlInputPasien.add(txtNo_HpPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 220, -1));

        txtAlamatPasien.setColumns(20);
        txtAlamatPasien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAlamatPasien.setRows(5);
        jScrollPane1.setViewportView(txtAlamatPasien);

        pnlInputPasien.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 220, 90));

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        pnlInputPasien.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 100, 30));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setText("Ubah");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlInputPasien.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("ID");
        pnlInputPasien.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblId_Pasien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblId_Pasien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlInputPasien.add(lblId_Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 40, 20));

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        pnlInputPasien.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 80, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnlInputPasien.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 100, 30));

        ComboStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Merah", "Kuning", "Hijau", "Putih", "Hitam" }));
        ComboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboStatusActionPerformed(evt);
            }
        });
        pnlInputPasien.add(ComboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("No Ruang");
        pnlInputPasien.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        TxtNoRuangan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnlInputPasien.add(TxtNoRuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 220, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/unnamed.png"))); // NOI18N
        pnlInputPasien.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 310));

        pnlTblPasien.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblPasien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblPasien.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tblPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPasienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPasien);

        txtCariPasien.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton14.setText("Cari");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        jLabel24.setText("cari berdasarkan id pasien");

        javax.swing.GroupLayout pnlTblPasienLayout = new javax.swing.GroupLayout(pnlTblPasien);
        pnlTblPasien.setLayout(pnlTblPasienLayout);
        pnlTblPasienLayout.setHorizontalGroup(
            pnlTblPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblPasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTblPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                    .addGroup(pnlTblPasienLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlTblPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(pnlTblPasienLayout.createSequentialGroup()
                                .addComponent(txtCariPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(29, 29, 29))
        );
        pnlTblPasienLayout.setVerticalGroup(
            pnlTblPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblPasienLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(pnlTblPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(txtCariPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPasienLayout = new javax.swing.GroupLayout(pnlPasien);
        pnlPasien.setLayout(pnlPasienLayout);
        pnlPasienLayout.setHorizontalGroup(
            pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasienLayout.createSequentialGroup()
                .addComponent(pnlInputPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTblPasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlPasienLayout.setVerticalGroup(
            pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasienLayout.createSequentialGroup()
                .addGroup(pnlPasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPasienLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(pnlInputPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPasienLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(pnlTblPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlPasien, "cardPasien");

        pnlDokter.setBackground(new java.awt.Color(255, 255, 255));

        pnlInputDokter.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("ID");

        lblId_dokter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblId_dokter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Nama");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Spesialis");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Alamat");

        txtNama_Dokter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtSpesialis_Dokter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAlamat_Dokter.setColumns(20);
        txtAlamat_Dokter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAlamat_Dokter.setRows(5);
        jScrollPane3.setViewportView(txtAlamat_Dokter);

        simpanDok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        simpanDok.setText("Simpan");
        simpanDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanDokActionPerformed(evt);
            }
        });

        UpdateDok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdateDok.setText("Update");
        UpdateDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDokActionPerformed(evt);
            }
        });

        HapusDok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HapusDok.setText("Hapus");
        HapusDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusDokActionPerformed(evt);
            }
        });

        ResetDok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ResetDok.setText("Reset");
        ResetDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetDokActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Username");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Password");

        txtUsernameDok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtPasswordDok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Nomor Hp");

        txtNoHpDok.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lvlDokter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lvlDokter.setText("Dokter");

        javax.swing.GroupLayout pnlInputDokterLayout = new javax.swing.GroupLayout(pnlInputDokter);
        pnlInputDokter.setLayout(pnlInputDokterLayout);
        pnlInputDokterLayout.setHorizontalGroup(
            pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputDokterLayout.createSequentialGroup()
                        .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel19))
                        .addGap(27, 27, 27)
                        .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsernameDok, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNama_Dokter)
                            .addGroup(pnlInputDokterLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblId_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lvlDokter)
                                .addGap(8, 8, 8))
                            .addComponent(jScrollPane3)))
                    .addGroup(pnlInputDokterLayout.createSequentialGroup()
                        .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel11)
                            .addComponent(jLabel20))
                        .addGap(25, 25, 25)
                        .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPasswordDok)
                            .addComponent(txtSpesialis_Dokter, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNoHpDok)))
                    .addGroup(pnlInputDokterLayout.createSequentialGroup()
                        .addComponent(simpanDok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateDok, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HapusDok, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResetDok, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlInputDokterLayout.setVerticalGroup(
            pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputDokterLayout.createSequentialGroup()
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputDokterLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputDokterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlInputDokterLayout.createSequentialGroup()
                                .addComponent(lblId_dokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addGroup(pnlInputDokterLayout.createSequentialGroup()
                                .addComponent(lvlDokter, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama_Dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsernameDok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordDok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoHpDok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpesialis_Dokter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(pnlInputDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanDok)
                    .addComponent(UpdateDok)
                    .addComponent(HapusDok)
                    .addComponent(ResetDok))
                .addGap(87, 87, 87))
        );

        pnlTblDokter.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane4MouseClicked(evt);
            }
        });

        tblDokter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblDokter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblDokter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDokter.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tblDokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDokterMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDokter);

        txtCariDokter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton12.setText("Cari");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Cetak");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        jLabel13.setText("Cari id dokter");

        javax.swing.GroupLayout pnlTblDokterLayout = new javax.swing.GroupLayout(pnlTblDokter);
        pnlTblDokter.setLayout(pnlTblDokterLayout);
        pnlTblDokterLayout.setHorizontalGroup(
            pnlTblDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDokterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTblDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblDokterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlTblDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblDokterLayout.createSequentialGroup()
                                .addComponent(txtCariDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblDokterLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)))
        );
        pnlTblDokterLayout.setVerticalGroup(
            pnlTblDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblDokterLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlTblDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(txtCariDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTblDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDokterLayout = new javax.swing.GroupLayout(pnlDokter);
        pnlDokter.setLayout(pnlDokterLayout);
        pnlDokterLayout.setHorizontalGroup(
            pnlDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDokterLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlInputDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTblDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDokterLayout.setVerticalGroup(
            pnlDokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInputDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlTblDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlUtama.add(pnlDokter, "cardDokter");

        pnlAdmin.setBackground(new java.awt.Color(255, 255, 255));

        pnlInputAdmin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("ID");

        lblId_Akun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblId_Akun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Nama");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Alamat");

        txtNamaAkun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAlamatAkun.setColumns(20);
        txtAlamatAkun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAlamatAkun.setRows(5);
        jScrollPane7.setViewportView(txtAlamatAkun);

        simpanDok1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        simpanDok1.setText("Simpan");
        simpanDok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanDok1ActionPerformed(evt);
            }
        });

        UpdateDok1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdateDok1.setText("Update");
        UpdateDok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDok1ActionPerformed(evt);
            }
        });

        HapusDok1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        HapusDok1.setText("Hapus");
        HapusDok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusDok1ActionPerformed(evt);
            }
        });

        ResetDok1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ResetDok1.setText("Reset");
        ResetDok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetDok1ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Username");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Password");

        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Nomor Hp");

        txtNomorHpAkun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblLevel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLevel.setText("Admin");

        txtEmailAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Email");

        javax.swing.GroupLayout pnlInputAdminLayout = new javax.swing.GroupLayout(pnlInputAdmin);
        pnlInputAdmin.setLayout(pnlInputAdminLayout);
        pnlInputAdminLayout.setHorizontalGroup(
            pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputAdminLayout.createSequentialGroup()
                        .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26))
                        .addGap(27, 27, 27)
                        .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNamaAkun)
                            .addGroup(pnlInputAdminLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblId_Akun, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLevel)
                                .addGap(8, 8, 8))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                    .addGroup(pnlInputAdminLayout.createSequentialGroup()
                        .addComponent(simpanDok1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateDok1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HapusDok1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResetDok1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInputAdminLayout.createSequentialGroup()
                        .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29))
                        .addGap(25, 25, 25)
                        .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmailAdmin)
                            .addComponent(txtPassword)
                            .addComponent(txtNomorHpAkun))))
                .addContainerGap())
        );
        pnlInputAdminLayout.setVerticalGroup(
            pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInputAdminLayout.createSequentialGroup()
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInputAdminLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel22)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInputAdminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlInputAdminLayout.createSequentialGroup()
                                .addComponent(lblId_Akun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addGroup(pnlInputAdminLayout.createSequentialGroup()
                                .addComponent(lblLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomorHpAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInputAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanDok1)
                    .addComponent(UpdateDok1)
                    .addComponent(HapusDok1)
                    .addComponent(ResetDok1))
                .addGap(71, 71, 71))
        );

        pnlTblAdmin.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane8MouseClicked(evt);
            }
        });

        tblAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblAdmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblAdmin);

        txtCariAdmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton13.setText("Cari");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        jLabel14.setText("cari id admin");

        javax.swing.GroupLayout pnlTblAdminLayout = new javax.swing.GroupLayout(pnlTblAdmin);
        pnlTblAdmin.setLayout(pnlTblAdminLayout);
        pnlTblAdminLayout.setHorizontalGroup(
            pnlTblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblAdminLayout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(pnlTblAdminLayout.createSequentialGroup()
                        .addComponent(txtCariAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        pnlTblAdminLayout.setVerticalGroup(
            pnlTblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTblAdminLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlTblAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(txtCariAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlInputAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInputAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlTblAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlUtama.add(pnlAdmin, "cardAkun");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/unnamed.png"))); // NOI18N
        pnlUtama.add(jLabel8, "card6");

        pnlSurat.setBackground(new java.awt.Color(255, 255, 255));
        pnlSurat.setName("cardSurat"); // NOI18N

        pnlTampilSurat.setBackground(new java.awt.Color(255, 255, 255));

        lblLevel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLevel1.setText("Surat Rujukan");

        jScrollPane10.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane10MouseClicked(evt);
            }
        });

        tblSurat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblSurat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tblSurat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblSurat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuratMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tblSurat);

        javax.swing.GroupLayout pnlTampilSuratLayout = new javax.swing.GroupLayout(pnlTampilSurat);
        pnlTampilSurat.setLayout(pnlTampilSuratLayout);
        pnlTampilSuratLayout.setHorizontalGroup(
            pnlTampilSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTampilSuratLayout.createSequentialGroup()
                .addGroup(pnlTampilSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLevel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlTampilSuratLayout.setVerticalGroup(
            pnlTampilSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTampilSuratLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCariAdmin1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton15.setText("Cari");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSuratLayout = new javax.swing.GroupLayout(pnlSurat);
        pnlSurat.setLayout(pnlSuratLayout);
        pnlSuratLayout.setHorizontalGroup(
            pnlSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuratLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuratLayout.createSequentialGroup()
                        .addComponent(txtCariAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlTampilSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(478, 478, 478))
        );
        pnlSuratLayout.setVerticalGroup(
            pnlSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuratLayout.createSequentialGroup()
                .addComponent(pnlTampilSurat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSuratLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCariAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15))
                .addGap(0, 117, Short.MAX_VALUE))
        );

        pnlUtama.add(pnlSurat, "cardSurat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardPasien");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardDokter");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardAkun");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPasienMouseClicked
        // TODO add your handling code here:
        int row = tblPasien.getSelectedRow();
        String id_pasien = tblPasien.getValueAt(row, 0).toString();
        String nama = tblPasien.getValueAt(row, 1).toString();
        String no_hp = tblPasien.getValueAt(row, 2).toString();
        String alamat = tblPasien.getValueAt(row, 3).toString();
        String status = tblPasien.getValueAt(row, 4).toString();
        String no_ruang = tblPasien.getValueAt(row, 5).toString();
        lblId_Pasien.setText(id_pasien);
        txtNama_Pasien.setText(nama);
        txtNo_HpPasien.setText(no_hp);
        txtAlamatPasien.setText(alamat);
        TxtNoRuangan.setText(no_ruang);
    }//GEN-LAST:event_tblPasienMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        //String id = lblId_Pasien.getText();
        //int id_pasien = Integer.parseInt(id);
        String nama = txtNama_Pasien.getText();
        String no_hp = txtNo_HpPasien.getText();
        String alamat = txtAlamatPasien.getText();
        String status = ComboStatus.getSelectedItem().toString();//
        String no_ruang = TxtNoRuangan.getText();
        Pasien pas = new Pasien(0,nama, no_hp, alamat,status,no_ruang);
        exec.ExecutePasien ePas = new exec.ExecutePasien();
        int hasil = ePas.insertData(pas);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDataPasien();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String id_pasien = lblId_Pasien.getText();
        exec.ExecutePasien ePas = new exec.ExecutePasien();
        int hasil = ePas.hapusData(id_pasien);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus"); 
            setDataPasien();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = lblId_Pasien.getText();
        int id_pasien = Integer.parseInt(id);
        String nama = txtNama_Pasien.getText();
        String alamat = txtAlamatPasien.getText();
        String status = ComboStatus.getSelectedItem().toString();
        String no_hp = txtNo_HpPasien.getText();
        String no_ruang = TxtNoRuangan.getText();
        Pasien pas = new Pasien(id_pasien,nama, no_hp, alamat,status,no_ruang);
        exec.ExecutePasien ePas = new exec.ExecutePasien();
        int hasil = ePas.ubahData(pas);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDataPasien();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        hapus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblDokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDokterMouseClicked
        // TODO add your handling code here:
        int row = tblDokter.getSelectedRow();
        String id_dok = tblDokter.getValueAt(row, 0).toString();
        String nama = tblDokter.getValueAt(row, 1).toString();
        String spesialis = tblDokter.getValueAt(row, 2).toString();
        String no_hp = tblDokter.getValueAt(row, 3).toString();
        String alamat = tblDokter.getValueAt(row, 4).toString();
        String uname = tblDokter.getValueAt(row, 5).toString();
        String pass = tblDokter.getValueAt(row, 6).toString();
        String level = tblDokter.getValueAt(row, 7).toString();
        lblId_dokter.setText(id_dok);
        txtNama_Dokter.setText(nama);
        txtSpesialis_Dokter.setText(spesialis);
        txtAlamat_Dokter.setText(alamat);
        txtUsernameDok.setText(uname);
        txtPasswordDok.setText(pass);
        lvlDokter.setText(level);
    }//GEN-LAST:event_tblDokterMouseClicked

    private void jScrollPane4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane4MouseClicked

    private void simpanDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanDokActionPerformed
        // TODO add your handling code here:
        String nama = txtNama_Dokter.getText();
        String spesialis = txtSpesialis_Dokter.getText();
        String alamat = txtAlamat_Dokter.getText();
        String username = txtUsernameDok.getText();
        String pass = txtPasswordDok.getText();
        String nohp = txtNoHpDok.getText();
        Dokter dok = new Dokter(0,nama, spesialis,nohp, alamat,username,pass,"Dokter");
        exec.ExecuteDokter eDok = new exec.ExecuteDokter();
        int hasil = eDok.insertData(dok);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDataDokter();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_simpanDokActionPerformed

    private void UpdateDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDokActionPerformed
        // TODO add your handling code here:
        String id = lblId_dokter.getText();
        int id_dok = Integer.parseInt(id);
        String nama = txtNama_Dokter.getText();
        String alamat = txtAlamat_Dokter.getText();
        String spesialis = txtSpesialis_Dokter.getText();
        String username = txtUsernameDok.getText();
        String pass = txtPasswordDok.getText();
        String nohp = txtNoHpDok.getText();
        Dokter dok = new Dokter(id_dok,nama, spesialis,nohp, alamat,username,pass,"Dokter");
        exec.ExecuteDokter eDok = new exec.ExecuteDokter();
        int hasil = eDok.ubahData(dok);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDataDokter();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
    }//GEN-LAST:event_UpdateDokActionPerformed

    private void HapusDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusDokActionPerformed
        // TODO add your handling code here:
        String id_dok = lblId_dokter.getText();
        exec.ExecuteDokter eDok = new exec.ExecuteDokter();
        int hasil = eDok.hapusData(id_dok);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus"); 
            setDataDokter();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_HapusDokActionPerformed

    private void ResetDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetDokActionPerformed
        // TODO add your handling code here:
        hapus2();
    }//GEN-LAST:event_ResetDokActionPerformed

    private void ComboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboStatusActionPerformed

    private void simpanDok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanDok1ActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String level = "Admin";
        String nama = txtNamaAkun.getText();
        String no_hp = txtNomorHpAkun.getText();
        String email = txtEmailAdmin.getText();
        String alamat = txtAlamatAkun.getText();
        Admin admin = new Admin(0,nama,username,password,level,no_hp,email,alamat);
        exec.ExecuteAdmin eDmin = new exec.ExecuteAdmin();
        int hasil = eDmin.insertData(admin);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            setDataAdmin();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di simpan");
        }
    }//GEN-LAST:event_simpanDok1ActionPerformed

    private void UpdateDok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDok1ActionPerformed
        // TODO add your handling code here:
        String id = lblId_Akun.getText();
        int id_akun = Integer.parseInt(id);
        String username = txtUsername.getText();
        String pass = txtPassword.getText();
        String nama = txtNamaAkun.getText();
        String no_hp = txtNomorHpAkun.getText();
        String alamat = txtAlamatAkun.getText();
        String email = txtEmailAdmin.getText();
        Admin admin = new Admin(id_akun,nama,username,pass,"Admin",no_hp,email, alamat);
        exec.ExecuteAdmin eDmin = new exec.ExecuteAdmin();
        int hasil = eDmin.ubahData(admin);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
            setDataAdmin();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
        }
    }//GEN-LAST:event_UpdateDok1ActionPerformed

    private void HapusDok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusDok1ActionPerformed
        // TODO add your handling code here:
        String id_admin = lblId_Akun.getText();
        exec.ExecuteAdmin eDmin = new exec.ExecuteAdmin();
        int hasil = eDmin.hapusData(id_admin);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus"); 
            setDataAdmin();
        }else{
            JOptionPane.showMessageDialog(null, "Data gagal di hapus");
        }
    }//GEN-LAST:event_HapusDok1ActionPerformed

    private void ResetDok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetDok1ActionPerformed
        // TODO add your handling code here:
        hapus3();
    }//GEN-LAST:event_ResetDok1ActionPerformed

    private void tblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminMouseClicked
        // TODO add your handling code here:
        int row = tblAdmin.getSelectedRow();
        String id_Admin = tblAdmin.getValueAt(row, 0).toString();
        String nama = tblAdmin.getValueAt(row, 1).toString();
        String username = tblAdmin.getValueAt(row, 2).toString();
        String password = tblAdmin.getValueAt(row, 3).toString();
        String level = tblAdmin.getValueAt(row, 4).toString();
        String no_hp = tblAdmin.getValueAt(row, 5).toString();
        String email = tblAdmin.getValueAt(row, 6).toString();
        String alamat = tblAdmin.getValueAt(row, 7).toString();
        lblId_Akun.setText(id_Admin);
        txtNamaAkun.setText(nama);
        txtPassword.setText(password);
        txtEmailAdmin.setText(email);
        txtPassword.setText(password);
        txtNomorHpAkun.setText(no_hp);
        txtUsername.setText(username);
        txtAlamatAkun.setText(alamat);
    }//GEN-LAST:event_tblAdminMouseClicked

    private void jScrollPane8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane8MouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        setDataPasien1();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        setDataAdmin1();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        setDataDokter1();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void tblSuratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuratMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSuratMouseClicked

    private void jScrollPane10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane10MouseClicked

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        cl = (CardLayout) pnlUtama.getLayout();
        cl.show(pnlUtama, "cardSurat");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            tblDokter.print(PrintMode.FIT_WIDTH, new MessageFormat("DATA DOKTER"),null);
        } catch (PrinterException ex) {
            Logger.getLogger(MFormAdmin.class.getName()).log(Level.SEVERE,null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    private void hapus(){
        txtNama_Pasien.setText("");
        txtAlamatPasien.setText("");
        txtNo_HpPasien.setText("");
        lblId_Pasien.setText("");
    }
    private void hapus2(){
        txtNama_Dokter.setText("");
        txtAlamat_Dokter.setText("");
        txtSpesialis_Dokter.setText("");
        lblId_dokter.setText("0");
    }
    private void hapus3(){
        txtNamaAkun.setText("");
        txtAlamatAkun.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtAlamatAkun.setText("");
        txtNomorHpAkun.setText("");
        txtEmailAdmin.setText("");
        lblLevel.setText("Admin");
        lblId_Akun.setText("0");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MFormAdmin().setVisible(true);
            }
        });
    }
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboStatus;
    private javax.swing.JButton HapusDok;
    private javax.swing.JButton HapusDok1;
    private javax.swing.JButton ResetDok;
    private javax.swing.JButton ResetDok1;
    private javax.swing.JTextField TxtNoRuangan;
    private javax.swing.JButton UpdateDok;
    private javax.swing.JButton UpdateDok1;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblId_Akun;
    private javax.swing.JLabel lblId_Pasien;
    private javax.swing.JLabel lblId_dokter;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLevel1;
    private javax.swing.JLabel lvlDokter;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlDokter;
    private javax.swing.JPanel pnlInputAdmin;
    private javax.swing.JPanel pnlInputDokter;
    private javax.swing.JPanel pnlInputPasien;
    private javax.swing.JPanel pnlPasien;
    private javax.swing.JPanel pnlSurat;
    private javax.swing.JPanel pnlTampilSurat;
    private javax.swing.JPanel pnlTblAdmin;
    private javax.swing.JPanel pnlTblDokter;
    private javax.swing.JPanel pnlTblPasien;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JButton simpanDok;
    private javax.swing.JButton simpanDok1;
    private javax.swing.JTable tblAdmin;
    private javax.swing.JTable tblDokter;
    private javax.swing.JTable tblPasien;
    private javax.swing.JTable tblSurat;
    private javax.swing.JTextArea txtAlamatAkun;
    private javax.swing.JTextArea txtAlamatPasien;
    private javax.swing.JTextArea txtAlamat_Dokter;
    private javax.swing.JTextField txtCariAdmin;
    private javax.swing.JTextField txtCariAdmin1;
    private javax.swing.JTextField txtCariDokter;
    private javax.swing.JTextField txtCariPasien;
    private javax.swing.JTextField txtEmailAdmin;
    private javax.swing.JTextField txtNamaAkun;
    private javax.swing.JTextField txtNama_Dokter;
    private javax.swing.JTextField txtNama_Pasien;
    private javax.swing.JTextField txtNoHpDok;
    private javax.swing.JTextField txtNo_HpPasien;
    private javax.swing.JTextField txtNomorHpAkun;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordDok;
    private javax.swing.JTextField txtSpesialis_Dokter;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsernameDok;
    // End of variables declaration//GEN-END:variables
}
